# SPDX-FileCopyrightText: 2024 Joel Kociolek
# SPDX-FileCopyrightText: 2020 Zach Daniel
#
# SPDX-License-Identifier: MIT

version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: "daily"
