name: CI
on:
  push:
    tags:
      - "v*"
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ash-ci:
    strategy:
      fail-fast: false
      matrix:
        mysql-version: ["8.0"]
    uses: lejoko/ash_mysql/.github/workflows/ash-ci.yml@main
    with:
      mysql: true
      mysql-version: ${{matrix.mysql-version}}
    secrets:
      hex_api_key: ${{ secrets.HEX_API_KEY }}
