# SPDX-FileCopyrightText: 2024 Joel Kociolek
# SPDX-FileCopyrightText: 2020 Zach Daniel
#
# SPDX-License-Identifier: MIT

name: CI
on:
  push:
    tags:
      - "v*"
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ash-ci:
    strategy:
      fail-fast: false
      matrix:
        mysql-version: ["8.0"]
    uses: ash-project/ash/.github/workflows/ash-ci.yml@main
    with:
      mysql: true
      ash_mysql: true
      mysql-version: ${{matrix.mysql-version}}
      reuse: true
    secrets:
      hex_api_key: ${{ secrets.HEX_API_KEY }}
